const router = {
    Home: '/',
    Login: '/login',
    Signup: '/signup',
    Resetpass: '/resetpass',
    Students: '/students',
    Lectures: '/lectures',
    UserProfile: '/userProfile',
    Project: '/projects',
    ProjectDetails: '/projects/:id',
    RegisterMajors: '/registerMajors',
    RegisterProject: '/registerProject',
    History: '/history',
    CreateProject: '/projects/create',
    StudentReport: '/students/report',
    Scoring: '/lectures/scoring',
    GuideLogin: '/guideLogin',
    GroupManager: '/GroupManager',
};
export default router;
